name: Publish wiki (regular)

on:
  schedule:
    - cron: '35 */4 * * *'
  workflow_dispatch:

concurrency:
  group: wiki
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: ./update-wiki.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
